### ISSUE TITLE
I wrote a lightweight, open source, tracking-free comment engine

### ISSUE THREAD

**Issue by adtac** [solid/solid-apps#11]
Hi. [stewsnooze from HackerNews](https://news.ycombinator.com/item?id=14206218) pointed me to this place. I created an open source alternative to something like Disqus with zero user tracking a couple of days ago. It's hosted here in Github: https://github.com/adtac/commento

I dunno if this fits your requirements for the comments and discussion service (it doesn't have voting atm, but I'm planning on implementing it), but I thought I could just create an issue here :)

**Comment by Mitzi-Laszlo** [comment]
Hi @adtac, 

Thank you for your input, let me know if there are any concrete actions you suggest to take and how to go about it.

Mitzi
