### ISSUE TITLE
IDEA: Embed solid app installer in app SVG image

### ISSUE THREAD

**Issue by mediaprophet** [solid/solid-apps#14]
SeeAlso: https://github.com/solid/vocab/issues/28 

The idea is to make use of SVG metadata field, to install a new solid app, into a solid pod.

seeAlso: https://www.w3.org/TR/SVG/metadata.html

**Comment by Mitzi-Laszlo** [comment]
Hi @mediaprophet, 

Thank you for your input, let me know if there are any concrete actions you suggest to take and how to go about it.

Mitzi

**Comment by mediaprophet** [comment]
Owing to behaviours, I left your solid community sometime ago and am
considering how to best help alternatives, such as globalCoin powered
solutions.  Where publishing work freely, good ideas get taken up, and I
don't need to put up with poor moral grammar.

Let's ensure all outstanding matters are closed. I want nothing more to do
with you.

I've closed out my w3c account but have Been advised their provenance
policy is different to the one demonstrated here, so,  I'm unable to
distort history in any better way as may best suit your needs
