### ISSUE TITLE
Finance Manager

### ISSUE THREAD

**Issue by ichbestimmtnicht** [solid/solid-apps#15]
Please add a Finance Manager like [Firefly-iii](https://github.com/firefly-iii/firefly-iii) to the wishlist. :)

**Comment by Mitzi-Laszlo** [comment]
added

**Comment by TallTed** [comment]
@Mitzi-Laszlo - The request was to "add a Finance Manager _**like**_ Firefly-iii to the wishlist", not to add [Firefly-iii](https://github.com/firefly-iii/firefly-iii) itself, presumably because it isn't (or at least, doesn't appear to be) Solid-based.
