### ISSUE TITLE
change master branch to gh-pages

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-apps#25]
This would enable us to host live demos of apps via the repo.

Anyone see any issues with this?

**Comment by megoth** [comment]
I like the idea - but how would it be wrt granting permissions to resources from these Demo-applications? If one application is trusted, are all?

If so, this might "just" be another reason for us to be hypervigilant in terms of which applications we list and allow to be run from gh-pages.

**Comment by melvincarvalho** [comment]
@megoth it's a good point and ties into trusted origins, which has been put into NSS 5 and requires more thought.

The gh-pages itself doesnt change that, it just makes one fewer step for those that want their own app area, or fork it.

Totally agree that hyper vigilance is important in this regard.  But that's probably a different, and possibly longer conversation.  A good one tho, and possibly needed.

**Comment by melvincarvalho** [comment]
I've changed the default branch to gh-pages.  That will give us more options going forward.  Let's open a new issue before adding actual apps tho.
