### ISSUE TITLE
Firefly-III Not a Solid App?

### ISSUE THREAD

**Issue by tmciver** [solid/solid-apps#58]
The finance management application [Firefly-III](https://firefly-iii.org/) is listed as a Solid app but this does not appear to be the case (I inquired about this [here](https://github.com/firefly-iii/firefly-iii/issues/2525)).

@Mitzi-Laszlo it looks like you're the one who added that app to the list.  Do you know if someone else has done the work to make it Solid compatible?

**Comment by Vinnl** [comment]
Inspecting the Git history, it appears that @TallTed [had already spotted this](https://github.com/solid/solid-apps/pull/45#discussion_r295349825). Apparently it was [a request](https://github.com/solid/solid-apps/issues/15) to add it to the list that people _wanted_ to have Solid support; not apps that actually support it.

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/solid-apps/pull/59

**Comment by Mitzi-Laszlo** [comment]
https://forum.solidproject.org/t/what-app-would-you-love-to-see-on-solid/525/61
