### ISSUE TITLE
Add description to https://referendum.signons.fr

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-apps#60]

**Comment by michielbdejong** [comment]
@Mitzi-Laszlo as per our email thread with the app devs, do you want to have a look at this?

**Comment by Mitzi-Laszlo** [comment]
See https://github.com/solid/solid.github.io/pull/213 where I had a go at incorporating the issue. If there's anything missing, submit a pull request on https://github.com/solid/solid.github.io/blob/master/pages/use-solid/apps.md
