### ISSUE TITLE
Move solid-file-widget to new libraries list

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-apps#61]
solid-file-widget looks awesome, I want to check it out!
But I think it probably qualifies more as a component to form part of a Solid app than to be listed here as a Solid app in itself?

So once https://github.com/solid/process/issues/169 is resolved, I think we should move that entry over, from the apps list to the new libs list.

What do you think, @bourgeoa?

**Comment by bourgeoa** [comment]
I agree with your proposal

**Comment by michielbdejong** [comment]
It's actually listed twice, once as 'Solid Authorization Widget' and once as 'Solid File Widget'. Great widget though! Is it based on https://github.com/remotestorage/remotestorage-widget? Would be nice to upstream the changes to there maybe, so that there is one widget that allows remoteStorage, GoogleDrive, DropBox, and Solid.

**Comment by bourgeoa** [comment]
Yes It is inspired from remote-storage widget. I don't think it can be
merge on only one common widget, but will keep the idea

Le lun. 4 nov. 2019 à 15:37, Michiel de Jong <notifications@github.com> a
écrit :

**Comment by Mitzi-Laszlo** [comment]
See https://github.com/solid/solid.github.io/pull/213 where I had a go at incorporating the issue. If there's anything missing, submit a pull request on https://github.com/solid/solid.github.io/blob/master/pages/use-solid/apps.md
