### ISSUE TITLE
add https://sigmafied.com

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-apps#62]

**Comment by michielbdejong** [comment]
@SharonStrats the source code of this app is at https://github.com/SharonStrats/SOLIDLBSPrototype correct?

**Comment by Mitzi-Laszlo** [comment]
See https://github.com/solid/solid.github.io/pull/213 where I had a go at incorporating the issue. If there's anything missing, submit a pull request on https://github.com/solid/solid.github.io/blob/master/pages/use-solid/apps.md
