### ISSUE TITLE
LinkedPipes is down?

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-apps#63]
See https://github.com/linkedpipes/applications/issues/778 for more details.

**Comment by aorumbayev** [comment]
@michielbdejong , sorry for that, it's back up online again!

**Comment by Mitzi-Laszlo** [comment]
See https://github.com/solid/solid.github.io/pull/213 where I had a go at incorporating the issue. If there's anything missing, submit a pull request on https://github.com/solid/solid.github.io/blob/master/pages/use-solid/apps.md
