### ISSUE TITLE
add apps from CCO project

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-apps#65]
I remember there were two apps related to https://forum.solidproject.org/t/common-core-ontology-with-linked-data/1860/2, one of them being a calendar app, I think? Trying to remember the URLs.

**Comment by michielbdejong** [comment]
cc @JKReynolds, I think you were the main author of those apps?

**Comment by michielbdejong** [comment]
See also https://github.com/solid/vocab/issues/42#issuecomment-557464316

**Comment by Mitzi-Laszlo** [comment]
See https://github.com/solid/solid.github.io/pull/213 where I had a go at incorporating the issue. If there's anything missing, submit a pull request on https://github.com/solid/solid.github.io/blob/master/pages/use-solid/apps.md
