### ISSUE TITLE
add Jackson's apps

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-apps#66]
@jaxoncreed can you add all your apps to this list?

**Comment by jaxoncreed** [comment]
https://github.com/solid/solid-apps/pull/67

**Comment by Mitzi-Laszlo** [comment]
See https://github.com/solid/solid.github.io/pull/213 where I had a go at incorporating the issue. If there's anything missing, submit a pull request on https://github.com/solid/solid.github.io/blob/master/pages/use-solid/apps.md
