### ISSUE TITLE
Add Solid Linked Beer

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-apps#68]
https://forum.solidproject.org/t/we-would-like-to-get-feedback-on-our-social-linked-beer-app/2426?u=pietervaneverdingen

**Comment by Mitzi-Laszlo** [comment]
See https://github.com/solid/solid.github.io/pull/213 where I had a go at incorporating the issue. If there's anything missing, submit a pull request on https://github.com/solid/solid.github.io/blob/master/pages/use-solid/apps.md
