### ISSUE TITLE
WikiRDF tool - CSV to RDF tool

### ISSUE THREAD

**Issue by ghost** [solid/solid-apps#9]
relatedTo: https://github.com/AGLDWG/TR/issues/5 

Principle is to be able to export traditional OpenData, use a web service as is demonstrated by [UDUVUDU](http://dbpedia.exascale.info/) to identify mark-up concept and convert existing data non-[lod](http://lod-cloud.net/) data to linked-data resources. 

Perhaps optionally add a mapping interface and the means to do 'sameAs' references where appropriate.

Nice for people looking for a camping spot, or a toilet with a baby changeTable... 

very basic WIP is being mapped out using a [google spreadsheet](https://docs.google.com/spreadsheets/d/1wTnXEB8T21pRuA81cDYB9722e9oSz58jMy3R0EtXObw/edit?usp=sharing)  but [RedLink demonstrates the concept relatively easily for freetext](https://my.redlink.io/#/apps/DEMO/playground)

**Comment by Mitzi-Laszlo** [comment]
Hi @ghost, Let me know if there are any concrete actions that you would suggest to take.
